;;;; Nyxt Configuration
;;;
;;;

;; Values autogenerated from Nyxt settings...
(define-configuration (input-buffer)
  ((default-modes
    (pushnew 'nyxt/mode/emacs:emacs-mode
             %slot-value%))))

(defmethod customize-instance ((browser browser) &key)
           (setf (slot-value browser 'restore-session-on-startup-p) nil))

;;; Password Management
;; keepassxc (or password-store)

;;; KeePassXC Configuration -example-

;; (defmethod initialize-instance :after
;;            ((interface password:keepassxc-interface)
;;             &key &allow-other-keys)
;;   "It's obviously not recommended to set master password here,
;; as your config is likely unencrypted and can reveal your password to someone
;; peeking at the screen."
;;   (setf (password:password-file interface)
;;           "/path/to/your/passwords.kdbx"
;;         (password:key-file interface) "/path/to/your/keyfile"
;;         (password:yubikey-slot interface) "1:1111"))

;; (define-configuration nyxt/mode/password:password-mode
;;   ((nyxt/mode/password:password-interface
;;     (make-instance 'password:keepassxc-interface))))

;; (define-configuration buffer
;;   ((default-modes
;;     (append (list 'nyxt/mode/password:password-mode) %slot-value%))))
