;;   -*- mode: lisp-data; -*-
((:container
  ((elisp org-element--headline-cache)
   (elisp org-element--cache)
   (version "2.3"))
  :persist-file "b8/bea876-e164-4633-a10b-3b58dbb16d0a" :associated
  (:hash "f3d12fec480a1a0c0321e27d7b58e543" :file "/home/logoraz/Documents/denotes/reference/20230902T193608--guix-linux-config__gnome_guile_log.org" :inode 8297935)
  :expiry 30 :last-access 1721095207.1459928 :last-access-hr "2024-07-15T19:00:07-0700")
 (:container
  ((index "3.2"))
  :persist-file "1e/237207-641c-45e9-a8cd-ce2260fa6ea5" :associated nil :expiry never :last-access 1721095762.5336318 :last-access-hr "2024-07-15T19:09:22-0700"))
