;;;; Nyxt Configuration
;;;
;;;

;; Values autogenerated from Nyxt settings...
(define-configuration (input-buffer)
                      ((default-modes
                        (pushnew 'nyxt/mode/emacs:emacs-mode
                                 %slot-value%))))

(defmethod customize-instance ((browser browser) &key)
           (setf (slot-value browser 'restore-session-on-startup-p) nil))
