;;; Automatically generated by ‘recentf’ on Mon Jul 15 20:18:47 2024.

(setq recentf-list
      '(
        "~/.config/stumpwm/config"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
