;;;; dot-sbclrc.lisp -> .sbclrc - SBCL Initialization File

;;; CLPM Configuration for SBCL
;;; Ref: https://www.clpm.dev/
;;; Use CLPM with default configuration.
;;;
;;; Generated by CLPM 0.4.1

(require "asdf")
#-clpm-client
(when (asdf:find-system "clpm-client" nil)
  ;; Load the CLPM client if we can find it.
  (asdf:load-system "clpm-client")
  (when (uiop:symbol-call :clpm-client '#:active-context)
    ;; If started inside a context (i.e., with `clpm exec` or `clpm bundle exec`),
    ;; activate ASDF integration
    (uiop:symbol-call :clpm-client '#:activate-asdf-integration)))


;;; Configure SBCL to add CFFI's to GUIX profile for ASDF to find?
;;; Ref: https://github.com/atlas-engineer/nyxt/blob/master/documents/
;;;      README.org#developers-installation-guide
;;; (require "asdf")
;;; (let ((guix-profile (format nil "~a/.guix-profile/lib/" (uiop:getenv "HOME"))))
;;;   (when (and (probe-file guix-profile)
;;;              (ignore-errors (asdf:load-system "cffi")))
;;;     (push guix-profile
;;;           (symbol-value (find-symbol (string '*foreign-library-directories*)
;;;                                      (find-package 'cffi))))))
